services:
  undercover:
    container-name: undercover
    image: ${IMAGE:-ghcr.io/tommypreel/undercover:latest}
    ports:
      - "3000:80"
    environment:
      - PORT=3000
    restart: always
    networks:
      - web

networks:
  web:
    external: true
    name: web
